### ISSUE TITLE
`Taro.init()`; ERROR: assertion failed

### ISSUE THREAD

**Issue by Ismael-VC** [aviks/Taro.jl#13]
This happens when I try to execute `Taro.init`:
```julia

C:\Users\CSM>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

C:\Users\CSM>julia -q
julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> using Taro
Found libjvm @ C:\Program Files\Java\jre1.8.0_31\bin\server\

julia> Taro.init()
ERROR: assertion failed: ccall(jnifunc.GetVersion,Cint,(Ptr{JNIEnv},),penv) == J
NI_VERSION_1_6
 in init at C:\Users\CSM\.julia\v0.3\JavaCall\src\JavaCall.jl:457
 in init at C:\Users\CSM\.julia\v0.3\Taro\src\Taro.jl:13

julia> ccall(jnifunc.GetVersion,Cint,(Ptr{JNIEnv},),penv)
ERROR: JNIEnv not defined
```

First I got #2, after wich I defined `JAVA_LIB` @ `C:\Program Files\Java\jre1.8.0_31\bin\server\`

Where and how should I define `JNIEnv`? Does `Taro.jl` only works with Java 1.6? If so, I think this should be mentioned.

Thanks!

**Comment by aviks** [comment]
`JavaCall` currently only works with JDK1.7 (which defines `JNI_Version` as `1_6`), which is mentioned in JavaCall documentation.  Taro uses `JavaCall.jl` to make calls to Java libraries.  Yes, I should probably document this better. 

You could comment out the assertion in https://github.com/aviks/JavaCall.jl/blob/master/src/JavaCall.jl#L457 , and it will load under JDK 1.8. Most things should work, but I haven't enabled it because I haven't tested it enough on 1.8.

**Comment by Ismael-VC** [comment]
@aviks I've downgraded to Java 7 and I get this:

```julia
julia> using Taro
Found libjvm @ C:\Program Files\Java\jre7\bin\server\

julia> Taro.init();

julia> Taro.readxl("data.xls", "Sheet1", "A2:B40")
ERROR: assertion failed: obj.ptr != C_NULL
 in _jcall at C:\Users\CSM\.julia\v0.3\JavaCall\src\JavaCall.jl:273
 in jcall at C:\Users\CSM\.julia\v0.3\JavaCall\src\JavaCall.jl:236
 in readxl at C:\Users\CSM\.julia\v0.3\Taro\src\Taro.jl:118
 in readxl at C:\Users\CSM\.julia\v0.3\Taro\src\Taro.jl:100
```

Using this test file: [`data.xls`](https://drive.google.com/file/d/0B6RdFRPuTldoNnlaVUo1TzJJbDQ/view?usp=sharing).

Your example with the `df-test.xlsx` file works though. I don't know what I'm doing wrong and what does [`@assert obj.ptr != C_NULL`](https://github.com/aviks/JavaCall.jl/blob/master/src/JavaCall.jl#L273) means if I'm getting a `C_NULL`.

**Comment by Ismael-VC** [comment]
I've just tried with a very simple scratch test file, and it's the same. Perhaps it's something wrong with the format? It just happens with the files I create here, I don't understand but will try in another computer with different setup when I get home, thanks!

**Comment by aviks** [comment]
Hi Ismael, 

That assertion is essentially equivalent to a null pointer in Java. It is basically complaining that the return value from a Java method call is null. I had not figured out a cleaner way to handle it. Now that `julia 0.4` has the `Nullable` type, we should probably use that, but I'll need to rewrite the API for that. 

So essentially there were two reasons why you were getting a null. One, Taro currently doesn't like empty rows. So I deleted all empty rows from the file. Second, the sheet is not called 'Sheet1' . After these changes, 

```julia
julia> Taro.readxl("/Users/aviks/Downloads/data.xls", "Test History - REACTOR   000004", "A2:B37")
35x2 DataFrame
| Row | Type                 | AC_Mtr_  |
|-----|----------------------|----------|
| 1   | "Frame #"            | "127T"   |
| 2   | "NP Freq"            | 60.0     |
| 3   | "Volt"               | 440.0    |
| 4   | "FLA"                | 80.0     |
| 5   | "KW"                 | 74.6     |
| 6   | "HP"                 | 100.0    |
| 7   | "PF"                 | NA       |
| 8   | "Eff"                | NA       |
| 9   | "NP Speed"           | 1758.0   |
⋮
| 26  | "pF Ph 1 to Ground"  | "< 1000" |
| 27  | "ohm Ph 1 to 2"      | 0.00262  |
| 28  | "ohm Ph 2 to 3"      | 0.00278  |
| 29  | "ohm Ph 3 to 1"      | 0.00463  |
| 30  | "mH Ph 1 to 2"       | 0.255    |
| 31  | "mH Ph 2 to 3"       | 0.185    |
| 32  | "mH Ph 3 to 1"       | 0.23     |
| 33  | "Average Inductance" | 0.225    |
| 34  | "% Res. Imbalance"   | 38.48    |
| 35  | "% Ind. Imbalance"   | 17.16    |

```

**Comment by aviks** [comment]
To clarify, I think Taro SHOULD handle empty rows. I'll put in a fix as soon as I can, but for the moment, the workaround is to delete empty rows from the workbook.

**Comment by Ismael-VC** [comment]
Thank's again @aviks , I didn't realize sheets could be named and in the tests I did from scratch, sheets are labeled in Spanish because of locale settings!

Sadly those files are the (manual) output of another proprietary software (no API), so even while I can delete blank lines manually the idea is to process them in batch programmatically.

**Comment by aviks** [comment]
OK. Thanks, its good to get some feedback. 

I do intend to fix the the empty line issues. I need a way to handle NULL  in `JavaCall`. After that, it will be a simple `if` statement in `Taro`

I can't promise, but I'll try to do something over the weekend.

**Comment by Ismael-VC** [comment]
I understand and I'll very much appreciate that.

I've tried some things to work around this.

* Select areas of the table with no blank rows individually, ie in the example file, I hoped to extract 3 `DataFrames` (because its divided twice by blank rows) so I could concatenate them latter, but I got the same error, so it seems it's not a mater of just taking care in not selecting portions of the table with blank rows. 

* Reconstruct both columns from the string that represents the body returned by `Taro.extract`, but `NA`s are not represented by that string.

I managed to do it using the `read_excel` function from `Pandas.jl`, as a bonus I don't need to know neither the sheet name nor the rows-column area in advance, in this case:

```julia
julia> using Pandas
INFO: Loading help data...

julia> df = read_excel("data.xls")    # simpler API
WARNING *** file size (6367) not 512 + multiple of sector size (512)
   NamePlate Information     Unnamed: 1
0                   Type        AC Mtr.
1                Frame #           127T
2                NP Freq             60
3                   Volt            440
4                    FLA             80
5                     KW           74.6
6                     HP            100
7                     PF            NaN
8                    Eff            NaN
9               NP Speed           1758
10              OP Speed           1758
11                 Slots            NaN
12                  Bars            NaN
13                   NaN            NaN
14                   NaN            NaN
15             Test Date      2/25/2015
16             Test Time    12:17:05 PM
17         Test Location    Motor Leads
18                  User  Administrator
19         Tester Serial            NaN
20               MTAP ID            NaN
21                             Baseline
22             Frequency           1200
23           Charge Time            600
24               Voltage            500
25            Motor Temp             18
26                                  NaN
27         Measured Mohm         > 300G
28        Corrected Mohm         > 300G
29     pF Ph 1 to Ground         < 1000
30         ohm Ph 1 to 2        0.00262
31         ohm Ph 2 to 3        0.00278
32         ohm Ph 3 to 1        0.00463
33          mH Ph 1 to 2          0.255
34          mH Ph 2 to 3          0.185
35          mH Ph 3 to 1           0.23
36    Average Inductance          0.225
37      % Res. Imbalance          38.48
38      % Ind. Imbalance          17.16
```

Do you think that `Taro.jl` could be used in the future as an optional dependency of `DataFrames.jl` to load excel files like `Pandas.jl` does? Something like:

```julia
julia> Using DataFrames

julia> read_xl("test.xls")    # This depends on Taro
```

**Comment by aviks** [comment]
Hi @Ismael-VC 

Taro actually handled empty rows correctly. The sole cause of the assertion failure above was due to the incorrect sheet name. The name of the sheet in the original file was `Test History - REACTOR   000004A90000055F : 1817902143` which is longer than what Excel displayed on my machine. 

I have added better error messages, and added the facility to refer to sheets by numeric index, as well as load the first sheet if the sheet name or number is not specified. After these changes, 

```julia
julia> Taro.readxl("/Users/aviks/Downloads/data.xls", "A2:B40")
38x2 DataFrame
| Row | Type                 | AC_Mtr_  |
|-----|----------------------|----------|
| 1   | "Frame #"            | "127T"   |
| 2   | "NP Freq"            | 60.0     |
| 3   | "Volt"               | 440.0    |
| 4   | "FLA"                | 80.0     |
| 5   | "KW"                 | 74.6     |
| 6   | "HP"                 | 100.0    |
| 7   | "PF"                 | NA       |
| 8   | "Eff"                | NA       |
| 9   | "NP Speed"           | 1758.0   |
| 10  | "OP Speed"           | 1758.0   |
| 11  | "Slots"              | NA       |
| 12  | "Bars"               | NA       |
| 13  | NA                   | NA       |
⋮
| 25  | "Motor Temp"         | 18.0     |
| 26  | " "                  | NA       |
| 27  | "Measured Mohm"      | "> 300G" |
| 28  | "Corrected Mohm"     | "> 300G" |
| 29  | "pF Ph 1 to Ground"  | "< 1000" |
| 30  | "ohm Ph 1 to 2"      | 0.00262  |
| 31  | "ohm Ph 2 to 3"      | 0.00278  |
| 32  | "ohm Ph 3 to 1"      | 0.00463  |
| 33  | "mH Ph 1 to 2"       | 0.255    |
| 34  | "mH Ph 2 to 3"       | 0.185    |
| 35  | "mH Ph 3 to 1"       | 0.23     |
| 36  | "Average Inductance" | 0.225    |
| 37  | "% Res. Imbalance"   | 38.48    |
| 38  | "% Ind. Imbalance"   | 17.16    |
```

I've added a separate issue to infer the rectangular block that can be read. I'll need to figure out what heuristic to use to get the range of populated cells.

**Comment by Ismael-VC** [comment]
@aviks this is awesome, thanks so much! :smiley:
