### ISSUE TITLE
Check out ExcelReaders

### ISSUE THREAD

**Issue by davidanthoff** [aviks/Taro.jl#15]
Just a note, I created another package that reads Excel files https://github.com/davidanthoff/ExcelReaders.jl. The main difference is that it uses the python xlrd package under the hood.

My main motivation is that getting Taro (or more JavaCall) working on Windows was really quite tricky and I needed something that required less user config steps. The python interface on julia seems really stable, so I had less problems that way. Also, I got the whole thing working in no time on juliabox, another thing that was important for my use-case.

I borrowed some code from here (not much, really just the range to cell conversion etc.), please let me know if you want me to ack that somehow in the new package.

Also, probably best to have both packages co-exist for a while?

**Comment by aviks** [comment]
Yeah, no issues. This package is under the `MIT` license, and so no issues with borrowing code. 

I would be interested however in your feedback about using JavaCall on Windows. What issues did you face?

**Comment by davidanthoff** [comment]
It only works with Java 7, and there won't be updates for that from April 2015 on. JavaCall didn't find a normal Java 7 runtime installation, I had to manually set the paths (not a problem for me, but I'm working with others where that kind of fiddling is prohibitive), and finally things crashed with garbage collector errors for large files (I don't remember whether it was java or julia garbage collector errors). Also, it was not clear to me whether it would work on juliabox.

Python just seemed a simpler setup. Everyone I work with has anaconda installed already, so all dependencies are there already (including xlrd). Also, on juliabox it was a matter of ``pip install xlrd`` to get things working.

**Comment by davidanthoff** [comment]
I'm closing this, there is really nothing to do here :)
