### ISSUE TITLE
"using Taro" returns java error

### ISSUE THREAD

**Issue by Balinus** [aviks/Taro.jl#18]
Hi, tried using Taro but got the following error when I type "using Taro"

ERROR: Cannot find java library in: {"","/usr/lib/jvm/default-java/jre/lib/amd64/server","/usr/lib/jvm/default-java/jre/lib/server"}To override the search, set the JAVA_LIB environment variable to the directory containing libjvm.so
 in error at error.jl:21
 in findjvm at /home/user/.julia/v0.3/JavaCall/src/JavaCall.jl:85
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/user/.julia/v0.3/JavaCall/src/JavaCall.jl, in expression starting on line 88
while loading /home/user/.julia/v0.3/Taro/src/Taro.jl, in expression starting on line 3

I don't seem to have a "default-java" directory. I have a pretty standard Ubuntu 14.04 LTS installation.
Any ideas? Thanks!

**Comment by aviks** [comment]
Please set a JAVA_HOME environment variable pointing to the root of your java installation. I'll need to improve the error message.

**Comment by Balinus** [comment]
Great thanks! I needed to set a link "default_java" directory inside /usr/lib/jvm pointing towards my java directory. It worked!
