### ISSUE TITLE
Converting FO files results in errors

### ISSUE THREAD

**Issue by kskoeld** [aviks/Taro.jl#24]
Trying to create PDFs out of FO files just produces a bunch of errors.
Which FOP version is supported?
Tried `Taro.fo("fonts.fo","fonts.pdf")` and same format on all the attached fo files.
errors I got were:
fonts.fo
`WARN  The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (See position 38:2)
WARN  The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (See position 298:1)
WARN  The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (See position 558:2)
WARN  The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (See position 818:2)
WARN  The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (See position 1066:2)
WARN  The contents of fo:block line 9 exceed the available area in the inline-progression direction by 7000 millipoints. (See position 569:2)
WARN  Glyph "m" (0x6d, m) not available in font "Symbol".
INFO  Rendered page #1.
INFO  Rendered page #2.
INFO  Rendered page #3.
INFO  Rendered page #4.
INFO  Rendered page #5.`

region-1.fo
`WARN  Unknown formatting object "{http://www.antennahouse.com/names/XSL/Extensions}document-info" encountered (a child of fo:root}. (See position 4:85)
WARN  Unknown formatting object "{http://www.antennahouse.com/names/XSL/Extensions}document-info" encountered (a child of fo:root}. (See position 5:64)
ERROR:  'file:/data/notebook_home/PDF%20tests/region-1.fo:8:64: For "fo:simple-page-master", "fo:region-body" must be declared before "fo:region-before"! (See position 8:64)'`

[fo-files.zip](https://github.com/aviks/Taro.jl/files/238756/fo-files.zip)

**Comment by aviks** [comment]
Taro uses `FOP 2.0` . You can change this by editing `deps/build.jl` and making corresponding changes in `src/Taro.jl`, and then running` Pkg.build()`

Given that these are warnings and errors from FOP, i'm not sure if there is anything to be done in this package.

**Comment by aviks** [comment]
This file seems to have an antenna house extension, and is incorrectly formatted according to FOP. Closing, since there is nothing Taro can do about this.
