### ISSUE TITLE
JDK installed but Taro.init() crashes and requests JDK install on my mac

### ISSUE THREAD

**Issue by tcovert** [aviks/Taro.jl#27]
I have the most recent version of the JDK and Taro/JavaCall, julia 0.4.6 and Mac OS El Capitan.

When I run the following code, I get the supposedly harmless segfault, but then Julia crashes and I am presented a screen to install Java:

> julia> using Taro
> Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/server/libjvm.dylib
> 
> julia> Taro.init()
> 
> signal (11): Segmentation fault: 11
> unknown function (ip: 0x30f2522b4)
> No Java runtime present, requesting install.

java -version reports:

> java version "1.8.0_92"
> Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

What am I doing wrong?

**Comment by tcovert** [comment]
I solved this myself.  It turns out that I didn't have "Java for OS X", available here: https://support.apple.com/kb/DL1572?locale=en_US.  Installing this, and keeping the JDK I already had, fixed the issue.  

Any idea why I need both things?

**Comment by aviks** [comment]
Unfortunately, this is a bug in the Oracle JDK for Mac, which forces the install of the old apple VM. 

https://bugs.openjdk.java.net/browse/JDK-7131356
