### ISSUE TITLE
Package-Dependencies

### ISSUE THREAD

**Issue by cndesantana** [aviks/Taro.jl#4]
Dear all,

First of all, thank you for sharing this great package. It is really helpful!!

Just a minor comment:

The first time I loaded Taro, it gave me the following error message: 

"ERROR: StoredArray not defined"

So, I Installed "DataArrays" package and everything worked fine.

My question is: Would it be possible to analyze this kind of dependencies automatically? Just like happens with Debian packages: If I ask for the installation of a package A that depends on other packages B, C, and D, julia would be sure that B, C, and D are installed before proceeding with the installation of A. 

Is it a Julia limitation? Or a choice of package admin? Or just an accident?

Best,

Charles

**Comment by aviks** [comment]
This should all be fine now. Please reopen if you still have issues
